workdir: "3d_genome_s_pombe_120min"

organism: "Schizosaccharomyces pombe"

sra_ids:
- SRR5149266
- SRR5149267
- SRR5942528

hicpro_restriction_sites: "^GATC"

hicpro_resolutions:
- 10000

pastis_resolutions:
- 10000
