# Wording directory name, without space
workdir: "name_of_the_working_directory"

# Organism name
organism: "name of the organism"

# Sample identifiers
sra_ids:
- ID1
- ID2
- ID3
- ID4

# Restriction sites
hicpro_restriction_sites: "T^TAA"

# Ligation site
# This parameter is optional.
hicpro_ligation_site: "AAGCTAGCTT"

# Output resolutions for HiC-Pro
hicpro_resolutions:
- 20000
- 30000
- 40000
- 50000

# Output resolutions for Pastis
# should match the resolutions used in HiC-Pro.
# Fewer resolutions can be used.
pastis_resolutions:
- 50000
- 40000

# Verify inverted contigs
# Could be True or False
verify_contigs: False
