workdir: "name_of_the_working_directory"

organism: "name of the organism"

sra_ids:
- ID1
- ID2
- ID3
- ID4

hicpro_restriction_sites: "dpnii T^TAA"

# Choose appropriate resolution
hicpro_resolutions:
- 10000
- 20000
- 30000
- 40000
- 50000

# Choose appropriate resolution
pastis_resolutions:
- 50000
- 40000