workdir: "3d_genome_n_crassa"

organism: "Neurospora crassa"

sra_ids:
- SRR16761089
- SRR14362684
- SRR16761090
- SRR16761091
- SRR16761092

hicpro_restriction_sites: "dpnii T^TAA"

hicpro_resolutions:
- 20000
- 50000

pastis_resolutions:
- 20000
- 50000
