workdir: "3d_genome_n_crassa"

organism: "Neurospora crassa"

sra_ids:
- SRR2105869
- SRR2105870
- SRR2105871
- SRR2105872

hicpro_restriction_sites: "dpnii T^TAA"

hicpro_resolutions:
- 10000
- 20000
- 40000
- 50000

pastis_resolutions:
- 50000
- 40000