workdir: "3d_genome_s_pombe_80min"

organism: "Schizosaccharomyces pombe"

sra_ids:
- SRR5149264
- SRR5149265
- SRR5942527

hicpro_restriction_sites: "^GATC"

hicpro_resolutions:
- 10000

pastis_resolutions:
- 10000

verify_contigs: False

