workdir: "3d_genome_s_pombe_70min"

organism: "Schizosaccharomyces pombe"

sra_ids:
- SRR5149261
- SRR5149263

hicpro_restriction_sites: "^GATC"

hicpro_resolutions:
- 10000

pastis_resolutions:
- 10000

verify_contigs: False

