workdir: "3d_genome_s_pombe_60min"

organism: "Schizosaccharomyces pombe"

sra_ids:
- SRR5149259
- SRR5149260
- SRR5942526


hicpro_restriction_sites: "^GATC"

hicpro_resolutions:
- 10000

pastis_resolutions:
- 10000

verify_contigs: False

