workdir: "3d_genome_s_pombe_50min"

organism: "Schizosaccharomyces pombe"

sra_ids:
- SRR5149257
- SRR5149258

hicpro_restriction_sites: "^GATC"

hicpro_resolutions:
- 10000

pastis_resolutions:
- 10000

verify_contigs: False

