name: 3d-genome-builder-workflow
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  # fasterq-dump
  - sra-tools
  # pigz: parallel implementation of gzip
  - pigz
  # Python library to read fasta files
  - biopython
  # Create HiC-Pro config file with template
  - jinja2
  # HiCPlotter dependencies
  - scipy
  - matplotlib
  # Pastis config file
  - pandas
  # Pastis
  - scikit-learn
  # Iced: https://github.com/hiclib/iced
  # https://pypi.org/project/iced/
  - iced
  - pip:
    # https://github.com/hiclib/pastis
    # https://pypi.org/project/pastis/
    - pastis==0.4.0
