name: 3d-genome-builder
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - snakemake-minimal
  # Build DAG with Snakemake
  - graphviz
  # Code cleaning
  - black
  # FASTQ file manipulation
  # https://anaconda.org/bioconda/seqkit
  # https://bioinf.shenwei.me/seqkit/
  - seqkit
  # Fasta and PDB files manipulation
  - biopython
  - biopandas


  