name: 3d-genome-builder
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - snakemake-minimal
  # fasterq-dump
  - sra-tools
  # pigz: parralel implementation of gzip
  - pigz
  # Python library to read fasta files
  - biopython
  # Build DAG with Snakemake
  - graphviz
  # Create HiC-Pro config file with template
  - jinja2

  